#! /bin/sh
export SXHKD_SHELL=/usr/bin/bash

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 # 7 8 9 10

bspc config border_width 2
bspc config focused_border_color "#56949f"
bspc config normal_border_color "#908caa"
bspc config window_gap 8

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Sreenkey manage=off
bspc rule -a vlc state=floating
bspc rule -a mpv state=floating
bspc rule -a feh state=floating center=true
bspc rule -a imv state=floating center=true

feh --bg-fill $HOME/Pictures/bg/bg.jpg
xsetroot -cursor_name left_ptr
# keymapper &
dunst &
picom -b &
fcitx5 &
udiskie &

# change X11 scale
xrdb -merge ~/.Xresource &

# setproxy
sh /etc/profile.d/setproxy.sh &

# enable libinput-gestures
libinput-gestures-setup start

# lauch bar
polybar
