#! /bin/sh
export SXHKD_SHELL=/usr/bin/bash

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor eDP -d 1 2 3 4 5 6 # 7 8 9 10
bspc monitor HDMI-A-0 -d 7
bspc config border_width 2
bspc config focused_border_color "#56949f"
bspc config normal_border_color "#908caa"
bspc config window_gap 8

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Sreenkey manage=off
bspc rule -a vlc state=floating
bspc rule -a mpv state=floating
bspc rule -a feh state=floating center=true
bspc rule -a imv state=floating center=true

xrandr --output eDP --primary --mode 2560x1600 --rotate normal 
my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-A-0')
if [[ $my_laptop_external_monitor = *connected* ]]; then
    xrandr --output HDMI-A-0 --mode 1920x1080 --rotate normal --left-of eDP
fi

feh --bg-fill $HOME/Pictures/bg/bg2.jpg
xsetroot -cursor_name left_ptr
# keymapper &
dunst &
picom -b &
fcitx5 &
udiskie &

# change X11 scale
xrdb -merge ~/.Xresource &

# setproxy
sh /etc/profile.d/setproxy.sh &

# enable libinput-gestures
libinput-gestures-setup start &

# lauch bar
sh ~/.config/polybar/launch.sh
