#!/bin/bash

DIR="$HOME/.config/dunst/icons"

function send_notification() {
	local brightness_level=$(brightnessctl g)
	local icon_name=""
	# local brightness_percentage=$((brightness_level * 100 / 255))
	local brightness_percentage=$(echo "scale=0; ($brightness_level * 100 + 254) / 255" | bc)
	if [ "$brightness_percentage" -lt 30 ]; then
		icon_name="$DIR/brightness-low-svgrepo-com.svg"
	elif [ "$brightness_percentage" -lt 70 ]; then
		icon_name="$DIR/brightness-medium-svgrepo-com.svg"
	else
		icon_name="$DIR/brightness-high-svgrepo-com.svg"
	fi

	dunstify "$brightness_percentage%  " -i $icon_name -t 1000 -r 5555 -u low -h int:value:$(($brightness_percentage))
}

case $1 in
up)
	brightnessctl s 5%+
	send_notification
	;;
down)
	brightnessctl s 5%-
	send_notification
	;;
*)
	echo "Usage: $0 {up|down}"
	exit 1
	;;
esac
